[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      font-src 'self' fonts.gstatic.com gstatic.com *.gstatic.com *.jsdelivr.net;
      img-src 'self' data: *.arcana.network;
      script-src 'self' 'unsafe-inline' *.google-analytics.com *.googletagmanager.com *.marker.io polyfill.io *.jsdelivr.net *.netlify.app unpkg.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      frame-src *.arcana.network youtube.com https://www.youtube.com *.netlify.com;
      frame-ancestors 'self';
    '''